alpha_multiplier: 1.0
backup_entropy: false
batch_size: 256
bc_steps: 0
buffer_size: 10000000
checkpoints_path: null
cql_alpha: 1.0
cql_alpha_online: 1.0
cql_clip_diff_max: .inf
cql_clip_diff_min: -200
cql_importance_sample: true
cql_lagrange: false
cql_max_target_backup: true
cql_n_actions: 10
cql_target_action_gap: 0.8
cql_temp: 1.0
device: cuda
gamma: 0.99
env: relocate-cloned-v1
eval_freq: 5000
group: calql-pd-relocate-cloned-v1-multiseed-v0
online_steps: 1000000
n_episodes: 10
name: CalQL-PD
normalize: false
normalize_reward: false
orthogonal_init: true
policy_lr: 0.0001
project: CORL
qf_lr: 0.0003
seed: 0
soft_target_update_rate: 0.005
target_update_period: 1
q_n_hidden_layers: 3
reward_scale: 1.0
reward_bias: 0.0
use_automatic_entropy_tuning: true

calql_checkpoint: null
strict_load: true
learning_starts: 20000
training_freq: 32
utd: 1.0
sac_alpha: 0.2
autotune: true
max_grad_norm: 50.0
progressive_residual: true
prog_explore: 1
res_scale: 0.1
actor_lr: 3e-4
q_lr: 3e-4
critic_layer_norm: true
tau: 0.005