actor_lr: 3e-4
actor_dropout: 0.1
batch_size: 256
beta: 3.0
buffer_size: 10000000
checkpoints_path: null
device: cuda
gamma: 0.99
env: door-cloned-v1
eval_freq: 10000
group: IQL-PD-D4RL
iql_deterministic_actor: false
iql_tau: 0.8
online_steps: 1000000
n_episodes: 50
name: IQL-PolicyDecorator-door-cloned-v1
normalize: true
normalize_reward: false
qf_lr: 3e-4
project: CORL
seed: 0
eval_seed: 42
tau: 0.005
vf_lr: 3e-4

iql_checkpoint: null
strict_iql_load: true
base_iql_deterministic: true
learning_starts: 20000
training_freq: 32
utd: 1.0
sac_alpha: 0.2
autotune: true
max_grad_norm: 50.0
progressive_residual: true
prog_explore: 1
res_scale: 0.1
policy_lr: 3e-4
q_lr: 3e-4
critic_layer_norm: true