actor_lr: 3e-4
actor_dropout: 0.1
batch_size: 256
beta: 1.0
buffer_size: 10000000
checkpoints_path: null
device: cuda
discount: 0.99
env: cube-single-play-singletask-task3-v0
eval_freq: 5000
group: IQL-ogbench
iql_deterministic: false
iql_tau: 0.9
load_model: ''
offline_iterations: 1000000
online_iterations: 1000000
n_episodes: 50
name: IQL_cube-single-play-singletask-task3-v0
normalize: false
normalize_reward: false
qf_lr: 3e-4
project: CORL
seed: 0
tau: 0.005
vf_lr: 3e-4