backup_entropy: false
batch_size: 256
bc_steps: 0
buffer_size: 10000000
checkpoints_path: null
device: cuda
discount: 0.99
env: cube-double-play-singletask-task5-v0
eval_freq: 5000
group: rlpd-cube-double-play-singletask-task5-v0
load_model: ''
offline_iterations: 0
online_iterations: 1000000
mixing_ratio: 0.5
n_episodes: 50
name: RLPD
normalize: false
normalize_reward: false
orthogonal_init: true
policy_lr: 0.0001
project: CORL
qf_lr: 0.0003
seed: 0
soft_target_update_rate: 0.005
target_update_period: 1
q_n_hidden_layers: 3
reward_scale: 1.0
reward_bias: 0.0
use_automatic_entropy_tuning: true
is_sparse_reward: false