lr: 3e-4
batch_size: 256
buffer_size: 2000000
checkpoints_path: null
device: cuda
discount: 0.99
env: door-cloned-v1
eval_freq: 5000
group: FQL-D4RL
offline_iterations: 1000000
online_iterations: 1000000
n_episodes: 50
name: FQL_door-cloned-v1
normalize: true
normalize_reward: false
project: CORL
seed: 0
eval_seed: 42
tau: 0.005
alpha: 30000